"""用户、部门、刷新令牌和文档权限

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


# 升级：写这次要对表做的修改。
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_permissions',
    sa.Column('doc_key', sa.String(length=36), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('updated', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('doc_key')
    )
    op.create_table('document_shares',
    sa.Column('doc_key', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('doc_key', 'group_id')
    )
    op.create_index(op.f('ix_document_shares_group_id'), 'document_shares', ['group_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('expires', sa.String(length=32), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_username'), 'refresh_tokens', ['username'], unique=False)
    op.create_table('user_group_members',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('username', 'group_id')
    )
    op.create_index(op.f('ix_user_group_members_group_id'), 'user_group_members', ['group_id'], unique=False)
    op.create_table('user_groups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


# 回退：撤销 upgrade 做的修改。
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_groups')
    op.drop_index(op.f('ix_user_group_members_group_id'), table_name='user_group_members')
    op.drop_table('user_group_members')
    op.drop_index(op.f('ix_refresh_tokens_username'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_document_shares_group_id'), table_name='document_shares')
    op.drop_table('document_shares')
    op.drop_table('document_permissions')
    # ### end Alembic commands ###
